name: Run tests

on: push

jobs:
    phpunit:
        name: Run tests
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  tools: composer:v2
                  coverage: xdebug

            - name: Run composer install
              run: composer install --no-interaction --prefer-dist --optimize-autoloader

            - name: Prepare Laravel Application
              run: |
                  cp .env.example .env
                  php artisan key:generate

            - name: Directory Permissions
              run: chmod -R 777 storage bootstrap/cache

            - name: Setup Vite Manifest
              run: |
                  npm install
                  npm run build

            - name: Execute tests
              run: vendor/bin/pest --coverage-clover clover.xml

            - name: Generate test coverage badge
              uses: timkrase/phpunit-coverage-badge@v1.2.0
              with:
                coverage_badge_path: 'badge-coverage.svg'
                push_badge: true
                repo_token: ${{ secrets.GITHUB_TOKEN }}